name: kuza_revamped
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1 
  http: ^1.1.0
  provider: ^6.1.0
  go_router: ^12.1.0
  fluttertoast: ^8.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/card.JPG

